### ISSUE TITLE
Screen Space Overlay

### ISSUE THREAD

**Issue by OnurcanDnmez** [LanKuDot/game_modules#4]
Hi LanKuDot,
First of all thank you for this great project,
I'm trying to add this circular buttons to my main game menu, how can we use this ui menu on screen space overlay canvas.
Regards.

**Comment by LanKuDot** [comment]
Hi OnurcanDnmez,
Is your project a 3D project? I think it is the problem of transformation of coordinates. I will try to fix it.

**Comment by OnurcanDnmez** [comment]
My project is 2D card game.
Yes when i change canvas type to screen space overlay mode. Boxes looks Intertwined. 
It would be nice if we could identify the area we were covering.

Thank you.

**Comment by LanKuDot** [comment]
Hi, I solved the problem by converting the coordinates of input and boxes to the canvas space instead of the world space. The changes have been committed at branch [hotfix](https://github.com/LanKuDot/game_modules/tree/hotfix), you can get the modified version from here. Changes will be merged to the branch master, if there is no problem. Thanks.

**Comment by OnurcanDnmez** [comment]
Hi, works like a charm thank you for update. I commit a little code for avoiding when sliding button to trigger click event.

**Comment by LanKuDot** [comment]
Thanks. I am fixing other problems, and commits haven't been pushed yet. You can send a pull request first, or wait until I fixes the problem. I will accept the request after commits of my local repo updated.
